/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    rateLimit: RateLimit;
    'admin-invitations': AdminInvitation;
    works: Work;
    'work-documents': WorkDocument;
    'work-assets': WorkAsset;
    'api-idempotency-records': ApiIdempotencyRecord;
    articles: Article;
    'article-media': ArticleMedia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      account: 'accounts';
      session: 'sessions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    rateLimit: RateLimitSelect<false> | RateLimitSelect<true>;
    'admin-invitations': AdminInvitationsSelect<false> | AdminInvitationsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'work-documents': WorkDocumentsSelect<false> | WorkDocumentsSelect<true>;
    'work-assets': WorkAssetsSelect<false> | WorkAssetsSelect<true>;
    'api-idempotency-records': ApiIdempotencyRecordsSelect<false> | ApiIdempotencyRecordsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-media': ArticleMediaSelect<false> | ArticleMediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Users chosen display name
   */
  name: string;
  /**
   * The email of the user
   */
  email: string;
  /**
   * Whether the email of the user has been verified
   */
  emailVerified: boolean;
  /**
   * The image of the user
   */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
  accountStatus: 'pending_verification' | 'active' | 'suspended';
  termsVersion?: string | null;
  termsAcceptedAt?: string | null;
  loginFailureCount?: number | null;
  loginLockedUntil?: string | null;
  inventoryOutOfStockThreshold?: number | null;
  inventoryWarningThreshold?: number | null;
  /**
   * The role/ roles of the user
   */
  role?: ('admin' | 'user' | 'staff')[] | null;
  account?: {
    docs?: (number | Account)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  session?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  issuer: string;
  /**
   * The id of the account as provided by the SSO or equal to userId for credential accounts
   */
  accountId: string;
  /**
   * The id of the provider as provided by the SSO
   */
  providerId: string;
  /**
   * The user that the account belongs to
   */
  user: number | User;
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken?: string | null;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken?: string | null;
  /**
   * The id token for the account. Returned by the provider
   */
  idToken?: string | null;
  /**
   * The date and time when the access token will expire
   */
  accessTokenExpiresAt?: string | null;
  /**
   * The date and time when the refresh token will expire
   */
  refreshTokenExpiresAt?: string | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope?: string | null;
  /**
   * The hashed password of the account. Mainly used for email and password authentication
   */
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * The date and time when the session will expire
   */
  expiresAt: string;
  /**
   * The unique session token
   */
  token: string;
  createdAt: string;
  updatedAt: string;
  /**
   * The IP address of the device
   */
  ipAddress?: string | null;
  /**
   * The user agent information of the device
   */
  userAgent?: string | null;
  /**
   * The user that the session belongs to
   */
  user: number | User;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  /**
   * The identifier of the verification request
   */
  identifier: string;
  /**
   * The value to be verified
   */
  value: string;
  /**
   * The date and time when the verification request will expire
   */
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * Rate limits for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rateLimit".
 */
export interface RateLimit {
  id: number;
  /**
   * The key for the rate limit.
   */
  key: string;
  count: number;
  lastRequest: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations".
 */
export interface AdminInvitation {
  id: number;
  role: 'admin' | 'user' | 'staff';
  token: string;
  /**
   * The invitation is invalid after this time.
   */
  expiresAt: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  publicId: string;
  owner: number | User;
  kind: 'pattern' | 'board';
  title: string;
  state: 'draft' | 'active' | 'pending_deletion' | 'deleted';
  visibility: 'private';
  documentRevision: number;
  documentSha256: string;
  currentDocument?: (number | null) | WorkDocument;
  recoverableUntil?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-documents".
 */
export interface WorkDocument {
  id: number;
  owner: number | User;
  work: number | Work;
  revision: number;
  schemaVersion: number;
  kind: 'pattern' | 'board';
  document:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentSha256: string;
  documentByteSize: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-assets".
 */
export interface WorkAsset {
  id: number;
  publicId: string;
  owner: number | User;
  work: number | Work;
  role: 'original' | 'display' | 'thumbnail' | 'document' | 'export';
  status: 'upload_pending' | 'uploaded' | 'ready' | 'validation_failed' | 'orphaned' | 'pending_purge' | 'deleted';
  visibility: 'private';
  mimeType: string;
  detectedMimeType?: string | null;
  sizeBytes: number;
  sha256: string;
  storageKey: string;
  storageETag?: string | null;
  uploadExpiresAt?: string | null;
  confirmedAt?: string | null;
  orphanedAt?: string | null;
  purgeAfter?: string | null;
  sourceDocumentRevision?: number | null;
  sourceDocumentSha256?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-idempotency-records".
 */
export interface ApiIdempotencyRecord {
  id: number;
  actor: number | User;
  route: string;
  keySha256: string;
  requestSha256: string;
  state: 'in_progress' | 'completed';
  responseStatus?: number | null;
  responseBody?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  publicId: string;
  section: 'guides' | 'blog';
  slug: string;
  articleType: 'tool_guide' | 'faq' | 'creative' | 'product_tutorial' | 'case_study' | 'announcement';
  title: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  authorType: 'staff' | 'codex_assisted';
  authorDisplayName: string;
  sourceList?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contentQuality: {
    topicIntent?: string | null;
    factCheckStatus: 'not_started' | 'needs_review' | 'checked';
    editorNotes?: string | null;
  };
  seoSuggestions?: {
    seoTitle?: string | null;
    primaryTopic?: string | null;
    metaDescription?: string | null;
    twitterCard?: ('summary' | 'summary_large_image') | null;
  };
  status: 'draft';
  version: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-media".
 */
export interface ArticleMedia {
  id: number;
  publicId: string;
  article?: (number | null) | Article;
  uploader: number | User;
  status: 'upload_pending' | 'ready' | 'validation_failed' | 'orphaned' | 'deleted';
  mimeType: string;
  sizeBytes: number;
  sha256: string;
  storageKey: string;
  altText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null)
    | ({
        relationTo: 'rateLimit';
        value: number | RateLimit;
      } | null)
    | ({
        relationTo: 'admin-invitations';
        value: number | AdminInvitation;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'work-documents';
        value: number | WorkDocument;
      } | null)
    | ({
        relationTo: 'work-assets';
        value: number | WorkAsset;
      } | null)
    | ({
        relationTo: 'api-idempotency-records';
        value: number | ApiIdempotencyRecord;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-media';
        value: number | ArticleMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  emailVerified?: T;
  image?: T;
  createdAt?: T;
  updatedAt?: T;
  accountStatus?: T;
  termsVersion?: T;
  termsAcceptedAt?: T;
  loginFailureCount?: T;
  loginLockedUntil?: T;
  inventoryOutOfStockThreshold?: T;
  inventoryWarningThreshold?: T;
  role?: T;
  account?: T;
  session?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  createdAt?: T;
  updatedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  issuer?: T;
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rateLimit_select".
 */
export interface RateLimitSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  lastRequest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations_select".
 */
export interface AdminInvitationsSelect<T extends boolean = true> {
  role?: T;
  token?: T;
  expiresAt?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  publicId?: T;
  owner?: T;
  kind?: T;
  title?: T;
  state?: T;
  visibility?: T;
  documentRevision?: T;
  documentSha256?: T;
  currentDocument?: T;
  recoverableUntil?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-documents_select".
 */
export interface WorkDocumentsSelect<T extends boolean = true> {
  owner?: T;
  work?: T;
  revision?: T;
  schemaVersion?: T;
  kind?: T;
  document?: T;
  contentSha256?: T;
  documentByteSize?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-assets_select".
 */
export interface WorkAssetsSelect<T extends boolean = true> {
  publicId?: T;
  owner?: T;
  work?: T;
  role?: T;
  status?: T;
  visibility?: T;
  mimeType?: T;
  detectedMimeType?: T;
  sizeBytes?: T;
  sha256?: T;
  storageKey?: T;
  storageETag?: T;
  uploadExpiresAt?: T;
  confirmedAt?: T;
  orphanedAt?: T;
  purgeAfter?: T;
  sourceDocumentRevision?: T;
  sourceDocumentSha256?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "api-idempotency-records_select".
 */
export interface ApiIdempotencyRecordsSelect<T extends boolean = true> {
  actor?: T;
  route?: T;
  keySha256?: T;
  requestSha256?: T;
  state?: T;
  responseStatus?: T;
  responseBody?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  publicId?: T;
  section?: T;
  slug?: T;
  articleType?: T;
  title?: T;
  excerpt?: T;
  body?: T;
  authorType?: T;
  authorDisplayName?: T;
  sourceList?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contentQuality?:
    | T
    | {
        topicIntent?: T;
        factCheckStatus?: T;
        editorNotes?: T;
      };
  seoSuggestions?:
    | T
    | {
        seoTitle?: T;
        primaryTopic?: T;
        metaDescription?: T;
        twitterCard?: T;
      };
  status?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-media_select".
 */
export interface ArticleMediaSelect<T extends boolean = true> {
  publicId?: T;
  article?: T;
  uploader?: T;
  status?: T;
  mimeType?: T;
  sizeBytes?: T;
  sha256?: T;
  storageKey?: T;
  altText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}